### PR TITLE
download_url is deprecated

### PR DESCRIPTION
**Pull request by graingert**
And this like 404s

### CODE REVIEW

**Comment by mnot** [comment]
Do you have a link to the deprecation? It's still referenced on http://pythonhosted.org/setuptools/setuptools.html?highlight=download_url

In the meantime, see 48ff3ad.

**Comment by graingert** [comment]
download_url is ignored by pip and by default is no longer displayed on PyPI https://pypi.python.org/simple/uritemplate/

**Comment by mnot** [comment]
I see it in quite a few places, e.g.:
  https://pypi.python.org/pypi/uritemplate/0.6
  https://pypi.python.org/pypi/TermFeed/0.0.10

**Comment by graingert** [comment]
Yeah but they're ignored by PyPI see also this PEP https://www.python.org/dev/peps/pep-0438/ which aims to stop/reduce off-PyPI package hosting

**Pull request closed without merging**
