### PR TITLE
Don't depend on simplejson

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@mnot is this package still maintained? If not I require it in production and would be happy to start supporting it.

**Comment by sigmavirus24** [comment]
@graingert if it isn't, [uritemplate.py](/sigmavirus24/uritemplate) is API compatible (with [1 exception](https://github.com/sigmavirus24/uritemplate/issues/17)) and is willing to merge the two (although I'm not certain what "merging" would do at this point). We have 90% of the uritemplate-test tests integrated into our own tests. I didn't have time to finish writing shim code for the last 10%.

**Comment by mnot** [comment]
@jcgregorio any thoughts?

**Comment by graingert** [comment]
@sigmavirus24 what's the missing 10% of tests?

**Comment by jcgregorio** [comment]
This pull request looks good.

**Comment by sigmavirus24** [comment]
@graingert haven't worked on the Negative tests that are in the repository.

**Comment by graingert** [comment]
@mnot any chance of a release?

**Pull request merged**
