### PR TITLE
Merge uritemplate.py

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@mnot @sigmavirus24 what do you think? Is this worth going forward with at all?

**Comment by sigmavirus24** [comment]
@graingert this had been ignored in the past. I'd be happy to fix any issues people have migrating to uritemplate.py but with the one exception I noted, they shouldn't have problems. I'm also committed to maintaining uritemplate.py because I actually need it.

**Comment by mnot** [comment]
@graingert this is a complete rewrite with no indication of the purpose. What's going on here?

@sigmavirus24 - you haven't discussed anything on our issues list or made any pull requests, so how has this been "ignored"? Happy to have your input, but don't expect us to go searching for it.

**Comment by graingert** [comment]
Personally I just want "one-- and preferably only one --obvious way to do" uritemplate templating

@mnot until last week it seemed the uritemplate.py package was supported and uritemplate was not

As part of this merge I also see @sigmavirus24 getting access to the GitHub repo and PyPI

If that's not what you're interes

**Comment by sigmavirus24** [comment]
@mnot when I started uritemplate.py there was no activity here so I rewrote it from scratch to get the features I needed (parse once, expand N times being the biggest) and for fun. Other people said they had attempted to discuss merging the two projects (@pombredanne being one that comes to mind immediately).

They can remain entirely separate projects. I intentionally chose the same namespace so uritemplate.py could be a drop in replacement.

(Note: I've also worked on a RFC 3986 implementation because the other existing implementation was GPL'd and projects I'm involved with needed something that was not licensed under the GPL.)

**Comment by mnot** [comment]
@graingert - sure, but it's not prudent to give repo access to someone who shows up and does a code-dump. If you want to help move this repo forward, create issues, make well-reasoned pull requests, etc., just as in any open source project. I see you've started doing that, which is great -- just don't expect us to take a massive pull request and grant repo access without a stronger history of activity.

@sigmavirus24 - that sounds entirely reasonable. I think leaving them as separate projects and letting people decide what they want to use is a fine outcome; there need not be "only one."

**Comment by graingert** [comment]
No worries, I'm not after repo rights for myself either

**Pull request closed without merging**
